name: Terminal3

on: [push]

jobs:
  build:
    name:  Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      
      - uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: '2.1.x' 
      - name: Build
        run: dotnet build ./Version1/Terminal3/Terminal3.sln --no-restore
      
  unittests:      
    needs: build
    name:  Unit Testing
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK '2.1.x'
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '2.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Unit Tests
      run: dotnet test ./Version1/Terminal3/Terminal3Tests/Terminal3-UnitTests.csproj        
 
  regression:  
    needs: unittests 
    name: Regression
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK '2.1.x'
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '2.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Regression tests 
      run: dotnet build --configuration Release --no-restore
